[package]
name = "vesu"
version = "0.1.0"
cairo-version = "=2.11.4"
edition = "2024_07"

[lib]

[[target.starknet-contract]]
casm = true
sierra = true

[dependencies]
starknet = "2.11.4"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.46.0" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "c804e98" }
openzeppelin = "2.0.0"

[tool.fmt]
max-line-length = 120
sort-module-level-items = true

[[tool.snforge.fork]]
name = "Mainnet"
# url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_7"
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_8/rdvL5iHyAP1ZHb84DY8JR"
block_id.number = "1565065"

[tool.voyager]
pool = { path = "src/pool.cairo" }

[scripts]
buildRelease = "scarb --profile release build"
format = "scarb fmt && yarn prettier --write ."
checkFormat = "scarb fmt --check && yarn prettier --check ."
startDevnet = "./scripts/startDevnet.sh"
killDevnet = "lsof -t -i tcp:5050 | xargs kill"
createPool = "scarb --profile release build && node --loader ts-node/esm ./scripts/createPool.ts"
createPosition = "scarb --profile release build && node --loader ts-node/esm ./scripts/createPosition.ts"
checkShutdownStatus = "scarb --profile release build && node --loader ts-node/esm ./scripts/checkShutdownStatus.ts"
deployDevnet = "scarb --profile release build && node --loader ts-node/esm ./scripts/deployDevnet.ts"
deployMainnet = "scarb --profile release build && node --loader ts-node/esm ./scripts/deployMainnet.ts"
deploySepolia = "scarb --profile release build && node --loader ts-node/esm ./scripts/deploySepolia.ts"
deployExtensions = "scarb --profile release build && node --loader ts-node/esm ./scripts/deployExtensions.ts"
verifyPool = "scarb --profile release build && node --loader ts-node/esm ./scripts/verifyPool.ts"
checkGasReport = "scarb --profile release build && node --loader ts-node/esm ./scripts/gasReport.ts --check"
updateGasReport = "scarb --profile release build && node --loader ts-node/esm ./scripts/gasReport.ts --write"
print-contract-size = "scarb --profile release build && node --loader ts-node/esm ./scripts/print-contract-size.ts"
test = "snforge test --max-n-steps 100000000"
