name: Integration

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1

      - name: Configure Git
        run: git config --global --add url."https://${{ secrets.PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Step 2 - Install project
        run: yarn install --frozen-lockfile

      - name: Step 3 - Check correct formatting
        run: scarb run checkFormat

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out main branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Configure Git
        run: git config --global --add url."https://${{ secrets.PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Step 2 - Install project
        run: yarn install --frozen-lockfile

      - name: Step 3 - Check typescript errors
        run: yarn tsc
